### ISSUE TITLE
JMM Desktop error clipboard

### ISSUE THREAD

**Issue by Blackdixxa** [japanesemediamanager/jmmclient#137]
Hi,

I have and issue with JMM client.
When I try to avdump files the software complain about clipboard.
https://drive.google.com/file/d/0BwTB3YKZ53RiVFNYcHRZTWJXMXM/view?usp=sharing 
https://drive.google.com/open?id=0BwTB3YKZ53RiYTZicEJEcjlENHc&authuser=0

I don't know wher to look I'm starting to have a lot of anime to identify in anidb

**Comment by jmediamanager** [comment]
Has this always happened?
or only in the latest version of JMM?

**Comment by Blackdixxa** [comment]
It started on the latest version.3.4.2.18 really annoying issue

**Comment by AreFinstad** [comment]
this does not always happen, does happen too often tho IMO.
this did happen before in the old patches aswell but started really showing itself around Desember way before this the patch above.

didnt really report on this back then here but it is an issue and it does happen more than i would like.

this issue happens when highlighting the files the user wants to copy ED2K 

the errors that pops up reads as follows for me: 
"OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))"
![](http://puu.sh/g9bnU/2b11b3e227.png)

the issue seems to be resolved once you highlight a new file

**Comment by Blackdixxa** [comment]
Ok so I'm not crazy I've read many stuffs on the web regarding this issue seem like the method employed in the framework to call the clipboard is in cause.
I'm not a developper and can't help much

**Comment by AreFinstad** [comment]
well the issue wasn't there at all before the beta patches stated last November so something must have happened somewhere i guess.
atleast its a real issue tho not a major one as you can always just re highlight the files to get JMM to render a new screen for you.

**Comment by Blackdixxa** [comment]
I can't get past that message I must close the program to make it work again :s
I don't understand what you mean when you say it's working again.

**Comment by AreFinstad** [comment]
hmmm do you get the same message as me? because i have no issue just clicking ok on the pop-up and then just reselecting the files anew to get things working again.

maybe we dont have the same issue at all..... i wonder.

will do a restart of the server and upload it for the admin, maybe its a different issue.

**Comment by Blackdixxa** [comment]
No no I have the exact same message but when I select another file the message just pop-up again.
and the program becomes unresponsive I must restart it

**Comment by AreFinstad** [comment]
well i dont have that issue. it just pops up, i close it and move on.

**Comment by jmediamanager** [comment]
@Blackdixxa please try this patch and see if it fixes your issue

http://www.jmediamanager.org/latestdownloads/beta/JMMDesktop_Patch_137.zip

**Comment by Blackdixxa** [comment]
OMG thank you !!!
It worked the program opened in a flash and everything is working fine now !

**Comment by jmediamanager** [comment]
Ok I will commit the changes, and it will be part of the next official release

Note - the patch also includes some other changes that I couldn't exclude, and may not be tested properly yet (3.4.3.1)
http://japanesemediamanager.github.io/changes.html
