### ISSUE TITLE
[Question] Folder naming

### ISSUE THREAD

**Issue by saitoh183** [japanesemediamanager/jmmclient#151]
Is there a way to get jmm client to create a folder for a new series using the English Title and not the Main Title?

**Comment by jmediamanager** [comment]
Hi, sorry for the late response.
At the moment this is not possible, because it is hard coded to use the Main Title from AniDB.

I will change this to match the Series Name display based on user options
i.e. AniDB/TvDB / Language Preferences

![snap2](https://cloud.githubusercontent.com/assets/6645153/8586598/bb5c0cbe-2633-11e5-8078-63ec8878b883.jpg)
![snap6](https://cloud.githubusercontent.com/assets/6645153/8586599/bf6cc118-2633-11e5-9c6a-f9902ed2f89a.jpg)

**DEV NOTES**

VideoLocal - MoveFileIfRequired

Uses 
AniDB_Anime.MainTitle

Change to use
AnimeSeries.GetSeriesName()

**Comment by saitoh183** [comment]
Yeah, that is what I set thinking the folder would follow but it didnt

**Comment by ElementalCrisis** [comment]
I fixed this awhile back, let me know if it's still an issue @saitoh183.

**Comment by saitoh183** [comment]
Ok will let you know
