### ISSUE TITLE
Support for J-dramas/tokusatsu?

### ISSUE THREAD

**Issue by MightyBirdy** [japanesemediamanager/jmmclient#155]
Is this being added eventually?

**Comment by jmediamanager** [comment]
No I don't think I will ever add this, as there isn't any API's etc out there

**Comment by MightyBirdy** [comment]
TVDB seems to have them, it's just that the way those shows are set up works better with JMM than other oraganizers. 

http://thetvdb.com/?id=161051&tab=series for example
or http://thetvdb.com/?tab=season&seriesid=73694&seasonid=421361&lid=7

**Comment by AreFinstad** [comment]
why not just use another media server program for that?
like EMBY, Kodi or Plex.
all these 3 get their data from thetvdb and (EMBY even renames the files for you)
all you need to do is to make sure you have season folders in each series and such.
i would go for EMBY if you have the clients on your platform, otherwise go for Plex because of the all the different clients they have. 


tho to be fair when talking about JMM, i wish we could make our own series groups that isnt using AniDB at all, that way it will open the users for this type of stuff aswell as other type of media. would love to be able to manage everything with JMM TBH. (feel that local metadata is needed for this tho)

**Comment by MightyBirdy** [comment]
None of those can group shows and films under one tag the same way JMM does. They also have extremely picky support regarding extras.

**Comment by AreFinstad** [comment]
well you can always use more than one library in emby one for shows and one for movies. 
all tvdb metadata gets added like categories, channel it comes from and so on. other than that you can also add new custom tags aswell if needed. it can search and use all the different types of search criteria that JMM has.

you can have one library for your dramas and one for another without an issue. you just have to split them up in different folders. 

you say that it doesnt tag lke JMM does, yet it does....
also, picky support regarding extras? like clients? its not really lacking at all on those either: http://emby.media/download/

**Comment by MightyBirdy** [comment]
Extras as in specials, trailers, behind-the-scenes, etc.

I don't separate folders for dramas and tokusatsu the way Plex wants - a movie goes where it should chronologically. Putting it in its own folder doesn't make sense if it takes place within a series. And renaming and re-ordering doesn't work as efficiently as in JMM.

**Comment by AreFinstad** [comment]
emby has both folder import by moving to series location aswell as file renaming for series.
specials and such can easily just be put into  season 0 or a specials folder. alot of the time those specials are added to tvdb so emby should find out those for itself.
ofc if it isnt on tvdb then you can always add it youself unless its locked.
also nothing stops you at all to edit your metadata with the metadatamanager in emby.

yes plex is good and fine, but emby is so much better by a mile unless you really need the plex clients (not many that emby doesnt have tho)
