### ISSUE TITLE
Duplicate Buttons In Random Episode Window

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#178]
Hello,

In the Random Episode window, there's a duplicate button for play and watched/unwatched. 

![duplicate play watched](https://cloud.githubusercontent.com/assets/9443295/8888577/16670cea-3268-11e5-814b-fb9374cd0d81.jpg)

**Comment by AreFinstad** [comment]
there have always been two buttons for some reason.
the reason for this is most likely for multi file episodes (if you have different quality files of the same episode) the top play button will auto play according to whatever setting you have set JMM to, the other is to pick a specific file, if you have had say a 720p release and a 1080p release of the same episode it would have been listen under eachother.

this is not an issue IMO.

**Comment by jmediamanager** [comment]
Yes it is exactly as AreFinstad described it.
This is also available in other areas such as the episode list on a series.

The reason is where you have multiple files for a an episode.
1 - Where you are collecting blu-ray versions
2 - People like me who auto download all files from Commie/Horrible Subs, and then sort them out later
