### ISSUE TITLE
Resize Fanart And Rotating Fanart

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#179]
Hello,

At the moment we can resize Group/Series List, Poster and Episode Image but not the Fanart that displays for the series you're looking at. I'd like to request this be added. 

Also, at the moment the Fanart only changes when you refresh. Would it be possible to have the Fanart auto-change when you're viewing the series?

**Comment by AreFinstad** [comment]
practically the same issue as https://github.com/japanesemediamanager/jmmclient/issues/161
will add a note about fanart (because its true that its does not work right now) 

also, you can already change the size of fanart and you could so for years now.
just click the edit button on the top of the detail tab of a series and then resize it to what you want, the setting goes across all series and groups aswell. 
 (screen of the setting location)
http://d.pr/i/q8Od

**Comment by ElementalCrisis** [comment]
I know you can do it manually for each show, I was hoping for more of a global option like we have for the other images.

**Comment by AreFinstad** [comment]
like i said, the setting goes across every group. only thing is that aspect ratios are different depending on the fanart in question.

**Comment by ElementalCrisis** [comment]
Thanks for the video, for some reason when I tired before it only worked for that series. I just gave it a go and it works on all.

**Comment by jmediamanager** [comment]
Coolio
