### ISSUE TITLE
trakt sync on per series basis?

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#181]
saw you working on the Trakt 2.0 update and i had a thought that might be handy for some.
how about we have a Trakt sync button on each series page that will sync only that series with Trakt?
that way we can sync series as we go without doing a full sync.
really handy for when you are not using JMM to watch things and comes back to it.

**Comment by jmediamanager** [comment]
That functionality was actually already there.

However the full sync now is much more efficient.
It now gets the collection/history status from Trakt, and compares it locally.
Then it only updates where things don't match.

Even for a large collection it should be pretty quick now.
Although the first time it will take a while, since most people's Trakt sync is out of date.

I am testing it from my full collection over the next couple of weeks.

**Comment by AreFinstad** [comment]
good to hear that it will be faster. love having those site up-to-date.

**Comment by jmediamanager** [comment]
Actually I have changed my mind on this, I have found this function very useful, as I have gone through and fixed bad links on a series by series basis
