### ISSUE TITLE
While using the rename feature the CRC turns to all-zeroes

### ISSUE THREAD

**Issue by smokeofc** [japanesemediamanager/jmmclient#211]
While using the rename feature the CRC turns to all-zeroes.

Example: Episode 23 [v2][8-bit][00000000][AonE].avi

Running Windows 10 x64, is there a fix for this?

script:
IF T(!Movie) DO ADD 'Episode %enr '
IF T(Movie) DO ADD '%epn '
IF F(!1) DO ADD '[v%ver]'
DO ADD '[%crc]'
IF Z(8) DO ADD '[%bit-bit]'
IF Z(10) DO ADD '[%bit-bit]'
DO ADD '[%grp]'
IF I(cen) DO ADD '[Cencored]'
IF I(!cen) DO ADD '[Uncencored]'

**Comment by AreFinstad** [comment]
note: i got Win10 Pro x64 and does not have this issue, plz make a new log where you replicate the issue (delete the old log and then just do what you are suppose to do (reason for deleting the log is so that log isn't long with unnecessary info))

you should also inform about if you are manually using the Rename Script or got it to Auto Rename on Import.

**Comment by jmediamanager** [comment]
I will take a look to see if I can replicate

**Comment by smokeofc** [comment]
I'm using SQLite for the server, and am renaming manually untill I can figure this out (Creates a mess with several raw files of the same episode if the CRC isn't naming properly).

What logs are you after? I'm checking the log for the client (%programfiles(x86)%\JMM Desktop\logs), and they doesn't seem to update as I'm previewing the name changes. (I tried earlier applying them thinking that it was just a preview thing, but didn't change the crc, still all zeroes).

![jmm](https://cloud.githubusercontent.com/assets/13959015/9489355/d7e55246-4be0-11e5-9a8c-77a4ccb51a8c.PNG)

**Comment by jmediamanager** [comment]
Ok the problem here is that CRC calculations were broken under the following circumstances
- Using the Hasher DLL
- Elected not to calculate CRC's when hashing a file

In this scenario it is populating the database with zero's instead of a null value.
With the file renamer, if the value is null it will use the CRC provided by AniDB instead.

I will make a change to fix the zeroes, and also a migration script to remove all the zeroes that are already in the database. Once this is done the renamer should work correctly.

You may also want to turn on calculation of CRC's in your settings panel
JMM Desktop - Settings - Essential - Import Settings

**Comment by jmediamanager** [comment]
For my own reference

00000000
00000000000000000000000000000000
0000000000000000000000000000000000000000
