### ISSUE TITLE
Link To Online Documentation 

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#212]
Currently the only way to view the online documentation is to click the about button at the bottom. While not an urgent request having either a help tab at the top or a button somewhere that takes the user to the online documentation would be useful.

**Comment by AreFinstad** [comment]
i do agree with this, i guess this is an oversight.
on the About page we need links to the .io site for the info aswell as the issues pages of both JMMD and JMMS.
or instead of hiding it in the about page we could have a new button that says Report a Bug and that will give you those two links (atleast), it would therefor be more obvious for newer users and users that would not think about going into the About Page.

**Comment by ElementalCrisis** [comment]
I've added a link on the main navigation menu to the documentation and a link to the Discord server next to the RSS feed. I'll do a quick look through and see if there's any spots where a link to the relevant documentation page can be added.
