### ISSUE TITLE
Redesign setting watched state

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#55]
**Reported by buzzplayerProblem, Jun 8, 2013**

In the current version of JMMDesktop the watched state gets updated once the player gets closed this has several issues.

1. JMMDesktop gets unresponsive for some time when there are several files to be updated
2. When not closing the player while switching the animes/playlists - JMMDesktop starts doesnt know that I have watched something and restarts files that already been watched
3. When playing more files then the max length of the players history JMMDesktop cant set them all because the players history doesnt list the file anymore (MPC has a limit of 20 - so when watching more than 20 episode while not closing the player you gona have a problem - this can happen quite often when watching short animes like http://anidb.net/perl-bin/animedb.pl?show=anime&aid=8645 where every episode is only 5 minutes)

Maybe you can develop a filewatcher for the settings file of the players?!?

**Comment by Daemeron** [comment]
Correct me if I am wrong but this issue is referring to only mpc-hc right?

Since user is asked to change some options in MPC for watched state to work we could use its web interface which would make it work better. 

Other possibility here could be getting watched progress directly from mpc-hc window if we could identify element while iterating over child windows.

What do you think?

Btw. Maybe I was looking wrong way but I took some time locating mpc-hc settings file that also should store progress as checking `store in ini file` option is not mandatory for mpc-hc ability to remember file progress. Maybe someone is able to find it, I failed to do so...

**Comment by Daemeron** [comment]
Seems mpc-hc without ini setting checked stores playback data in registry. Getting duration from mpc-hc gui while iterating over windows seems like a bad idea now as there is no possibility to identify this element. Its identifier is randomly generated.

I decided to take the Web UI approach and I am currently developing it. Hopefully I will be able make pull request soon.
